### ISSUE TITLE
This is a fork

### ISSUE THREAD

**Issue by ferry-** [DafnyVSCode/Dafny-VSCode#37]
Hi,
Original author of https://github.com/ferry-/dafny-vscode here. While you have expanded my work to include many more features, you did not start off from scratch. Your git log even shows my commits
https://github.com/DafnyVSCode/Dafny-VSCode/commits/develop?after=ad2bd9e62133cb619eda1879431104b748b0ca55+420 at the very beginning, which you included into this repository without my permission.
You are not crediting me anywhere. The MIT license on my repo explicitly sets out "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." This is largely a matter of principle but you should include my name at least in the copyright notice of this project.

**Comment by fmehta** [comment]
Dear Jonathan
I am the person who supervised the students who worked on the first versions of this plugin and am currently trying to keep it alive so that I can use it for my course. I knew that the students were building upon the work done by you (which is, as you also mention quite evident from the commit logs and fork). I assumed that the students were in contact with you regarding their work. 
Regarding the copyright notice: this is something that I should have checked. I am very sorry that your name was not included till now and totally agree that the copyright notice needs to reflect your contribution. This morning, we have added your name to the top of all copyright notices and the "contributors" section of readme and made a new release so that this is visible to all users immediately.
Sorry again for this oversight,
Farhad Mehta
